version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: codecore
      MYSQL_DATABASE: universidad
      MYSQL_USER: admin
      MYSQL_PASSWORD: codecore
    volumes:
    #  - ./universidad.sql:/docker-entrypoint-initdb.d/universidad.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"

  backend:
    build:
      context: ./backend-pvds
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
#
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:8080"

volumes:
  mysql_data:

#sudo systemctl start docker
#docker-compose up 
